# Generated by Django 4.1.7 on 2023-07-12 06:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('blood_group', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Blood_Bank',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField()),
                ('quantity_donated_ml', models.FloatField(default=460, validators=[django.core.validators.MinValueValidator(460), django.core.validators.MaxValueValidator(500)])),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.blood')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=30)),
                ('employee_contact_no', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=50)),
                ('salary', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000000)])),
                ('job', models.CharField(max_length=20)),
                ('works_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.blood_bank')),
            ],
        ),
        migrations.CreateModel(
            name='Recieving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieving_date', models.DateField()),
                ('quantity_recieved_ml', models.FloatField(validators=[django.core.validators.MinValueValidator(460)])),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.blood')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('degree', models.CharField(max_length=30)),
                ('nurse_employee', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Myapp.employee')),
            ],
            bases=('Myapp.employee',),
        ),
        migrations.CreateModel(
            name='Shift_Incharge',
            fields=[
                ('qualification', models.CharField(max_length=30)),
                ('shift_incharge_employee', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Myapp.employee')),
            ],
            bases=('Myapp.employee',),
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('specialization', models.CharField(max_length=30)),
                ('technician_employee', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Myapp.employee')),
            ],
            bases=('Myapp.employee',),
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('recipient_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=30)),
                ('recipient_contact_no', models.CharField(max_length=11)),
                ('recipient_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(3)])),
                ('recipient_gender', models.CharField(max_length=1)),
                ('recipient_blood_grp', models.CharField(max_length=3)),
                ('recievs', models.ManyToManyField(related_name='recipients', through='Myapp.Recieving', to='Myapp.blood')),
            ],
        ),
        migrations.AddField(
            model_name='recieving',
            name='recipient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.recipient'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.FloatField()),
                ('stock_up_date', models.DateField()),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.blood')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.blood_bank')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.AutoField(primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=30)),
                ('donor_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(60)])),
                ('donor_gender', models.CharField(max_length=1)),
                ('donor_blood_grp', models.CharField(max_length=3)),
                ('donor_contact_no', models.CharField(max_length=11)),
                ('donates', models.ManyToManyField(related_name='donors', through='Myapp.Donation', to='Myapp.blood')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.donor'),
        ),
        migrations.AddField(
            model_name='blood_bank',
            name='stock',
            field=models.ManyToManyField(related_name='stock', through='Myapp.Inventory', to='Myapp.blood'),
        ),
    ]
