# Generated by Django 4.1.7 on 2023-07-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_quantity',
            field=models.FloatField(default=470),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='degree',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='shift_incharge',
            name='qualification',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='technician',
            name='specialization',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
