# Generated by Django 4.1.7 on 2023-07-13 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_alter_inventory_stock_quantity_alter_nurse_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock_quantity',
            field=models.FloatField(default=470, validators=[django.core.validators.MinValueValidator(470), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
