# Generated by Django 4.1.7 on 2023-07-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_alter_donor_donor_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_quantity',
            field=models.FloatField(),
        ),
    ]
