# Generated by Django 4.1.7 on 2023-07-15 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_alter_inventory_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='branch_id',
        ),
        migrations.AddField(
            model_name='inventory',
            name='branch_name',
            field=models.ForeignKey(default='Gulshan Branch2', on_delete=django.db.models.deletion.CASCADE, to='Myapp.blood_bank', to_field='branch_name'),
        ),
        migrations.AlterField(
            model_name='blood_bank',
            name='branch_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity_donated_ml',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recieving',
            name='quantity_recieved_ml',
            field=models.IntegerField(),
        ),
    ]
