# Generated by Django 4.1.7 on 2023-07-15 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_remove_inventory_branch_id_inventory_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='branch_name',
            field=models.ForeignKey(default='Gulshan Branch', on_delete=django.db.models.deletion.CASCADE, to='Myapp.blood_bank', to_field='branch_name'),
        ),
    ]
